package com.ak.contexta.domain.usecase

import com.ak.contexta.domain.LlmClient
import com.ak.contexta.domain.error.LlmFatalException
import com.ak.contexta.domain.error.LlmRecoverableExhaustedException
import com.ak.contexta.domain.model.ExampleSentence
import com.ak.contexta.domain.model.WordDetail
import com.ak.contexta.domain.model.WordSense
import com.ak.contexta.domain.repository.StatsRepository
import com.ak.contexta.domain.repository.VocabularyRepository
import com.ak.contexta.domain.repository.WordRepository
import io.mockk.coEvery
import io.mockk.coVerify
import io.mockk.mockk
import kotlinx.coroutines.test.runTest
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test

class AddWordUseCaseTest {

    private val wordRepository: WordRepository = mockk()
    private val vocabularyRepository: VocabularyRepository = mockk()
    private val statsRepository: StatsRepository = mockk()
    private val llmClient: LlmClient = mockk()

    private lateinit var useCase: AddWordUseCase

    @Before
    fun setUp() {
        useCase = AddWordUseCase(wordRepository, vocabularyRepository, statsRepository, llmClient)
    }

    // ─── 校验 ───────────────────────────────────────────────

    @Test
    fun `blank input is rejected`() = runTest {
        val result = useCase("   ")
        assertTrue(result is AddWordUseCase.AddWordResult.InvalidInput)
        assertTrue((result as AddWordUseCase.AddWordResult.InvalidInput).message.contains("请输入"))
    }

    @Test
    fun `non-letter input is rejected`() = runTest {
        assertTrue(useCase("1234") is AddWordUseCase.AddWordResult.InvalidInput)
        assertTrue(useCase("你好") is AddWordUseCase.AddWordResult.InvalidInput)
    }

    @Test
    fun `input longer than max length is rejected`() {
        val long = "a".repeat(AddWordUseCase.MAX_INPUT_LENGTH + 1)
        val error = AddWordUseCase.validate(long)
        assertTrue(error != null && error.contains("过长"))
    }

    @Test
    fun `valid word passes validation`() {
        assertNull(AddWordUseCase.validate("serendipity"))
        assertNull(AddWordUseCase.validate("ice cream"))
        assertNull(AddWordUseCase.validate("can't"))
    }

    @Test
    fun `no LLM call on invalid input`() = runTest {
        useCase("你好")
        coVerify(exactly = 0) { llmClient.call(any(), any()) }
        coVerify(exactly = 0) { wordRepository.findLocal(any()) }
    }

    // ─── 本地命中 ───────────────────────────────────────────

    @Test
    fun `existing word not in vocab is added to vocab and reported as AlreadyExists`() = runTest {
        val detail = sampleDetail(wordId = 1, isInVocabulary = false)
        coEvery { wordRepository.findLocal("serendipity") } returns detail
        coEvery { vocabularyRepository.addWord(1) } returns true
        coEvery { statsRepository.recordWordAdded() } returns Unit

        val result = useCase("Serendipity")

        assertTrue(result is AddWordUseCase.AddWordResult.AlreadyExists)
        val already = result as AddWordUseCase.AddWordResult.AlreadyExists
        assertEquals(detail, already.detail)
        assertTrue(already.addedToVocabulary)
        coVerify(exactly = 0) { llmClient.call(any(), any()) }
        coVerify(exactly = 1) { vocabularyRepository.addWord(1) }
        coVerify(exactly = 1) { statsRepository.recordWordAdded() }
    }

    @Test
    fun `existing word already in vocab returns without duplicate add`() = runTest {
        val detail = sampleDetail(wordId = 1, isInVocabulary = true)
        coEvery { wordRepository.findLocal("serendipity") } returns detail

        val result = useCase("serendipity")

        assertTrue(result is AddWordUseCase.AddWordResult.AlreadyExists)
        val already = result as AddWordUseCase.AddWordResult.AlreadyExists
        assertTrue(!already.addedToVocabulary)
        coVerify(exactly = 0) { vocabularyRepository.addWord(any()) }
        coVerify(exactly = 0) { statsRepository.recordWordAdded() }
        coVerify(exactly = 0) { llmClient.call(any(), any()) }
    }

    // ─── LLM 生成 ───────────────────────────────────────────

    @Test
    fun `word not in local dict is generated by LLM, saved and added to vocab`() = runTest {
        coEvery { wordRepository.findLocal("serendipity") } returns null
        coEvery { llmClient.call(any(), any()) } returns LlmClient.LlmResult(validXml, 0)
        coEvery {
            wordRepository.saveLlmResult(
                spellingDisplay = "Serendipity",
                phoneticIpa = "/ˌserənˈdɪpəti/",
                senses = any(),
                normalized = "serendipity"
            )
        } returns sampleDetail(wordId = 42, isInVocabulary = false)
        coEvery { vocabularyRepository.addWord(42) } returns true
        coEvery { statsRepository.recordWordAdded() } returns Unit

        val stages = mutableListOf<AddWordUseCase.Stage>()
        val result = useCase("serendipity") { stages.add(it) }

        assertTrue(result is AddWordUseCase.AddWordResult.Success)
        val success = result as AddWordUseCase.AddWordResult.Success
        assertEquals(42L, success.detail.wordId)
        assertTrue(success.addedToVocabulary)
        assertEquals(
            listOf(AddWordUseCase.Stage.CHECKING_LOCAL, AddWordUseCase.Stage.GENERATING),
            stages
        )
        coVerify(exactly = 1) { vocabularyRepository.addWord(42) }
        coVerify(exactly = 1) { statsRepository.recordWordAdded() }
    }

    @Test
    fun `LLM response without valid senses fails with friendly message`() = runTest {
        coEvery { wordRepository.findLocal("serendipity") } returns null
        coEvery { llmClient.call(any(), any()) } returns LlmClient.LlmResult("<spelling>x</spelling>", 0)

        val result = useCase("serendipity")

        assertTrue(result is AddWordUseCase.AddWordResult.Failed)
        val failed = result as AddWordUseCase.AddWordResult.Failed
        assertTrue(failed.message.contains("拼写"))
        coVerify(exactly = 0) { vocabularyRepository.addWord(any()) }
        coVerify(exactly = 0) { statsRepository.recordWordAdded() }
    }

    @Test
    fun `LlmFatalException maps to failure message`() = runTest {
        coEvery { wordRepository.findLocal("serendipity") } returns null
        coEvery { llmClient.call(any(), any()) } throws LlmFatalException("auth failed")

        val result = useCase("serendipity")

        assertTrue(result is AddWordUseCase.AddWordResult.Failed)
        val failed = result as AddWordUseCase.AddWordResult.Failed
        assertTrue(failed.message.contains("AI 服务暂不可用"))
    }

    @Test
    fun `LlmRecoverableExhaustedException maps to network failure message`() = runTest {
        coEvery { wordRepository.findLocal("serendipity") } returns null
        coEvery { llmClient.call(any(), any()) } throws LlmRecoverableExhaustedException("timeout")

        val result = useCase("serendipity")

        assertTrue(result is AddWordUseCase.AddWordResult.Failed)
        val failed = result as AddWordUseCase.AddWordResult.Failed
        assertTrue(failed.message.contains("网络不稳定"))
    }

    @Test
    fun `unexpected exception maps to generic failure`() = runTest {
        coEvery { wordRepository.findLocal("serendipity") } returns null
        coEvery { llmClient.call(any(), any()) } throws RuntimeException("boom")

        val result = useCase("serendipity")

        assertTrue(result is AddWordUseCase.AddWordResult.Failed)
    }

    // ─── 工具 ───────────────────────────────────────────────

    private fun sampleDetail(wordId: Long, isInVocabulary: Boolean): WordDetail {
        val sense = WordSense(
            id = 1,
            orderIndex = 1,
            partOfSpeech = "n.",
            chineseMeaning = "意外发现珍奇事物的运气",
            englishDefinition = "The occurrence and development of events by chance in a happy or beneficial way.",
            examples = listOf(
                ExampleSentence(
                    id = 1,
                    orderIndex = 1,
                    sentenceEn = "It was pure serendipity that we met.",
                    sentenceZh = "我们的相遇纯属幸运。",
                    isPrimary = true
                )
            )
        )
        return WordDetail(
            wordId = wordId,
            spellingDisplay = "Serendipity",
            phoneticIpa = "/ˌserənˈdɪpəti/",
            primarySense = sense,
            allSenses = listOf(sense),
            isInVocabulary = isInVocabulary,
            vocabularyEntryId = if (isInVocabulary) 7 else null
        )
    }

    private val validXml = """
        <spelling>Serendipity</spelling>
        <phonetic>/ˌserənˈdɪpəti/</phonetic>
        <sense>
          <partOfSpeech>n.</partOfSpeech>
          <chineseMeaning>意外发现珍奇事物的运气</chineseMeaning>
          <englishDefinition>The occurrence of events by chance in a happy way.</englishDefinition>
          <example>
            <en>It was pure serendipity that we met.</en>
            <zh>我们的相遇纯属幸运。</zh>
          </example>
        </sense>
    """.trimIndent()
}
