services:
  contexta-server:
    build:
      context: .
      platforms:
        - linux/arm64
        - linux/amd64
    container_name: contexta-server
    ports:
      - "8080:8080" # ⚠️注意！你的.env里PORT=8080，之前示例写的3000，这里要改成8080
    env_file:
      - ./.env # 读取宿主机server/.env，注入到容器内部
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./output:/app/output
    restart: unless‑stopped
